const sampleData = {
  products: [
    {
      name: 'Tristar Cookware Red',
      slug: 'tristar-cookware-red',
      category: "Stainless steel",
      description: 'Tristar Cookware Red',
      images: [
        '/images/sample-products/TS200.jpg',
        '/images/sample-products/TS200.jpg',
      ],
      price: 29.99,
      brand: 'Tri star',
      rating: 4.4,
      numReviews: 160,
      stock: 15,
      isFeatured: false,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Tristar Cookware Black',
      slug: 'tristar-cookware-black',
      category: "Stainless steel",
      description: 'Tristar Cookware Black',
      images: [
        '/images/sample-products/TS201.jpg',
        '/images/sample-products/TS201.jpg',
      ],
      price: 29.99,
      brand: 'Supreme',
      rating: 4.5,
      numReviews: 200,
      stock: 29,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {  
      name: 'Tristar Champagne Bucket',
      slug: 'tristar-champagne-bucket',
      category: "Stainless steel",
      description: 'Tristar Champagne Bucket',
      images: [
        '/images/sample-products/TS381.jpg',
        '/images/sample-products/TS381.jpg',
      ],
      price: 3.99,
      brand: 'Tri star',
      rating: 4.7,
      numReviews: 700,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    }, 
    {
      name: 'Tristar Champagne Bucket 20cm',
      slug: 'tristar-champagne-bucket-20',
      category: "Stainless steel",
      description: 'Tristar Champagne Bucket 20cm',
      images: [
        '/images/sample-products/TS382.jpg',
        '/images/sample-products/TS382.jpg',
      ],
      price: 5.99,
      brand: 'Tri star',
      rating: 4.7,
      numReviews: 700,
      stock: 5,
      isFeatured: false,
      banner: '/images/banner-1.jpg',
    },    
    {
      name: 'Supreme 3 Pcs Set',
      slug: 'supreme-3-pcs-set',
      category: "Stainless steel",
      description: 'Supereme 3 Pcs Set',
      images: [
        '/images/sample-products/TS36513.jpg',
        '/images/sample-products/TS36513.jpg',
      ],
      price: 39.99,
      brand: 'Supreme',
      rating: 4.8,
      numReviews: 77,
      stock: 15,
      isFeatured: false,
      banner: '/images/banner-1.jpg',
    },    
    {
      name: 'Sonex Diecast Set',
      slug: 'sonex-diecast-set',
      category: "Stainless steel",
      description: 'Sonex Diecast Set',
      images: [
        '/images/sample-products/52230.jpg',
        '/images/sample-products/52230.jpg',
      ],
      price: 45.00,
      brand: 'Sonex',
      rating: 4.8,
      numReviews: 198,
      stock: 15,
      isFeatured: true,
      banner: '/images/banner-3.jpg',
    },    
    {
      name: 'Sonex Fryingpan Set',
      slug: 'sonex-frying-set',
      category: "Stainless steel",
      description: 'Sonex Fryingpan Set',
      images: [
        '/images/sample-products/52282L.jpg',
        '/images/sample-products/52282L.jpg',
      ],
      price: 45.00,
      brand: 'Sonex',
      rating: 4.8,
      numReviews: 198,
      stock: 15,
      isFeatured: false,
      banner: '/images/banner-1.jpg',
    },    
    {
      name: 'Sonex Fryingpan 22cm',
      slug: 'sonex-frying-22cm',
      category: "Stainless steel",
      description: 'Sonex Fryingpan 22cm',
      images: [
        '/images/sample-products/53015.jpg',
        '/images/sample-products/53015.jpg',
      ],
      price: 23.00,
      brand: 'Sonex',
      rating: 4.8,
      numReviews: 98,
      stock: 190,
      isFeatured: false,
      banner: '/images/banner-1.jpg',
    },    
    {
      name: 'Royal Die-cast set',
      slug: 'royal-die-cast-set',
      category: "Stainless steel",
      description: 'Royal Die-cast set',
      images: [
        '/images/sample-products/D131163P.jpg',
        '/images/sample-products/D131163P.jpg',
      ],
      price: 23.00,
      brand: 'Sonex',
      rating: 4.8,
      numReviews: 98,
      stock: 190,
      isFeatured: false,
      banner: '/images/banner-1.jpg',
    }
  ],
};

export default sampleData;
